package egress

import (
	"encoding/json"
	"testing"
)

// parent_refs is the resolved owner of each pushed entity, keyed by the edge name
// the kit declared under entity_types[].parent_edges.
//
// It is the only way a component can populate an external foreign key: the entity
// as read carries no containment, because containment is an edge and an entity
// read projects columns. The manifest half of this pairing is asserted in
// manifest.TestValidateEgressSyncs_RejectsDuplicateParentEdge and
// _RejectsUnaddressableParentEdges — if the two disagree, a component waits on a
// key that never arrives.
//
// NOTE: no golden wire fixture yet. The fixtures in wire_golden_test.go are
// generated by marshalling the PLATFORM's internal/egress structs, and the
// platform does not carry parent_refs until OGA-822. Hand-writing one from the
// design document would only prove the SDK agrees with prose, which is exactly
// what that file's comment warns against. Regenerate with the platform.
func TestParentRefs_DecodesAndKeysOnTheDeclaredEdge(t *testing.T) {
	const body = `{
  "tenant_id": "sjcs",
  "external_system": "24k-core",
  "entity_type": "rec:Room",
  "mode": "bulk",
  "batch_id": "sjcs:core-sync:rec:Room:bulk:2:abc",
  "entities": [
    {
      "id": "019e38e3-room",
      "entity_type": "rec:Room",
      "properties": {"rdfs_label": "SAN 36A-L4-312"},
      "parent_refs": {
        "hasLocation": {
          "entity_id": "019e38e3-level",
          "external_record_id": "8f2c1d04-core-uuid"
        }
      }
    },
    {
      "id": "019e38e3-campus",
      "entity_type": "rec:Building"
    }
  ]
}`
	var req SyncRequest
	if err := json.Unmarshal([]byte(body), &req); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(req.Entities) != 2 {
		t.Fatalf("entities = %d, want 2", len(req.Entities))
	}

	ref, ok := req.Entities[0].ParentRefs["hasLocation"]
	if !ok {
		t.Fatalf("parent_refs is keyed on the declared edge name; got keys %v",
			keysOf(req.Entities[0].ParentRefs))
	}
	// The external id is what a foreign key needs; the entity id is for logging.
	if ref.ExternalRecordID != "8f2c1d04-core-uuid" {
		t.Errorf("external_record_id = %q, want the owner's external id", ref.ExternalRecordID)
	}
	if ref.EntityID != "019e38e3-level" {
		t.Errorf("entity_id = %q, want the owner's platform id", ref.EntityID)
	}

	// An ABSENT parent_refs means the entity is a root of that relation. It must
	// decode to an empty map and NOT be mistaken for an error — a campus root has
	// no parent, and omitting the foreign key is the correct outcome.
	if len(req.Entities[1].ParentRefs) != 0 {
		t.Errorf("a root entity carried parent_refs = %v, want none", req.Entities[1].ParentRefs)
	}
}

// An entity with no parent_refs must marshal WITHOUT the key, so the existing
// golden fixtures (generated from a platform that has no such field) still hold
// byte-for-byte. Without omitempty this addition would break every one of them.
func TestParentRefs_AbsentDoesNotAppearOnTheWire(t *testing.T) {
	raw, err := json.Marshal(Entity{ID: "e1", EntityType: "Equipment"})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if got := string(raw); got != `{"id":"e1","entity_type":"Equipment"}` {
		t.Errorf("entity marshalled as %s; an absent parent_refs must be omitted", got)
	}
}

func keysOf(m map[string]ParentRef) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
