package egress

import (
	"context"
	"encoding/json"
	"net/http"
	"reflect"
	"testing"
)

// Cross-repo wire drift guard.
//
// The platform's internal/egress structs and this package's are two independent
// declarations of ONE wire contract, living in different repositories. Nothing in
// either compiler sees the other, so a renamed JSON tag on either side is a
// silent, total integration break: an entity id that decodes to "" produces a
// batch the platform rejects as malformed, and it would pass every unit test in
// both repos.
//
// The fixtures below were GENERATED by marshalling the platform's own
// internal/egress.SyncRequest / SyncResponse (oga-platform, PR #814 branch
// feat/OGA-775-egress-sync at b076845a) and pasted verbatim. They are not
// hand-written from the design document, which would only prove the SDK agrees
// with a prose description.
//
// This guard catches drift on the SDK side of the pair. It cannot catch a
// platform-side rename by itself — that needs the mirror test in the platform
// repo, which imports this package and cross-decodes both directions.
const (
	platformRequestJSON = `{
  "tenant_id": "sjcs",
  "external_system": "24k-core",
  "entity_type": "Equipment",
  "mode": "bulk",
  "batch_id": "egress-sjcs-24k-core-Equipment-bulk-0001",
  "entities": [
    {
      "id": "eq-1",
      "entity_type": "Equipment",
      "properties": {
        "active": true,
        "floor": 3,
        "name": "AHU-1"
      }
    },
    {
      "id": "eq-2",
      "entity_type": "Equipment",
      "properties": {
        "name": "AHU-2"
      },
      "correlation": {
        "external_system": "24k-core",
        "external_record_id": "CORE-77"
      }
    },
    {
      "id": "eq-3",
      "entity_type": "Equipment"
    }
  ]
}`

	platformResponseJSON = `{
  "results": [
    {
      "id": "eq-1",
      "outcome": "created",
      "external_record_id": "CORE-90"
    },
    {
      "id": "eq-2",
      "outcome": "updated",
      "external_record_id": "CORE-77"
    },
    {
      "id": "eq-3",
      "outcome": "skipped"
    },
    {
      "id": "eq-4",
      "outcome": "failed",
      "error": "external system rejected payload: missing site"
    }
  ]
}`
)

// A platform-marshalled request must decode into the SDK structs with every
// field populated. Asserting field VALUES (not just a nil error) is the point:
// json.Unmarshal ignores a field whose tag does not match, so a renamed tag
// decodes without error and silently yields a zero value.
func TestSyncRequest_DecodesPlatformWire(t *testing.T) {
	var req SyncRequest
	if err := json.Unmarshal([]byte(platformRequestJSON), &req); err != nil {
		t.Fatalf("decode platform request: %v", err)
	}
	if req.TenantID != "sjcs" {
		t.Errorf("tenant_id = %q, want sjcs", req.TenantID)
	}
	if req.ExternalSystem != "24k-core" {
		t.Errorf("external_system = %q, want 24k-core", req.ExternalSystem)
	}
	if req.EntityType != "Equipment" {
		t.Errorf("entity_type = %q, want Equipment", req.EntityType)
	}
	if req.Mode != ModeBulk {
		t.Errorf("mode = %q, want %q", req.Mode, ModeBulk)
	}
	if req.BatchID != "egress-sjcs-24k-core-Equipment-bulk-0001" {
		t.Errorf("batch_id = %q", req.BatchID)
	}
	if len(req.Entities) != 3 {
		t.Fatalf("entities = %d, want 3", len(req.Entities))
	}

	first := req.Entities[0]
	if first.ID != "eq-1" || first.EntityType != "Equipment" {
		t.Errorf("entities[0] = %+v", first)
	}
	// A JSON number decodes into any as float64; a kit mapping properties must
	// expect that, so the fixture carries one and the test pins the type.
	if got, ok := first.Properties["floor"].(float64); !ok || got != 3 {
		t.Errorf("entities[0].properties[floor] = %#v, want float64(3)", first.Properties["floor"])
	}
	if first.Properties["name"] != "AHU-1" || first.Properties["active"] != true {
		t.Errorf("entities[0].properties = %#v", first.Properties)
	}
	if first.Correlation != nil {
		t.Errorf("entities[0].correlation = %+v, want nil (uncorrelated ⇒ create)", first.Correlation)
	}

	second := req.Entities[1]
	if second.Correlation == nil {
		t.Fatal("entities[1].correlation is nil: an already-correlated entity would be re-created, duplicating the external record")
	}
	if second.Correlation.ExternalSystem != "24k-core" || second.Correlation.ExternalRecordID != "CORE-77" {
		t.Errorf("entities[1].correlation = %+v", second.Correlation)
	}

	if third := req.Entities[2]; len(third.Properties) != 0 {
		t.Errorf("entities[2].properties = %#v, want empty (omitempty)", third.Properties)
	}
}

// An SDK-marshalled response must reproduce the platform's wire bytes exactly,
// including which fields omitempty drops.
func TestSyncResponse_MarshalsToPlatformWire(t *testing.T) {
	resp := SyncResponse{Results: []SyncResult{
		{ID: "eq-1", Outcome: OutcomeCreated, ExternalRecordID: "CORE-90"},
		{ID: "eq-2", Outcome: OutcomeUpdated, ExternalRecordID: "CORE-77"},
		{ID: "eq-3", Outcome: OutcomeSkipped},
		{ID: "eq-4", Outcome: OutcomeFailed, Error: "external system rejected payload: missing site"},
	}}
	got, err := json.MarshalIndent(resp, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if string(got) != platformResponseJSON {
		t.Errorf("SDK response wire differs from the platform's:\n got: %s\nwant: %s", got, platformResponseJSON)
	}
}

// And the reverse direction: the platform's response bytes decode into the SDK
// structs unchanged. This is what a kit-side test harness relies on.
func TestSyncResponse_DecodesPlatformWire(t *testing.T) {
	var resp SyncResponse
	if err := json.Unmarshal([]byte(platformResponseJSON), &resp); err != nil {
		t.Fatalf("decode platform response: %v", err)
	}
	want := []SyncResult{
		{ID: "eq-1", Outcome: OutcomeCreated, ExternalRecordID: "CORE-90"},
		{ID: "eq-2", Outcome: OutcomeUpdated, ExternalRecordID: "CORE-77"},
		{ID: "eq-3", Outcome: OutcomeSkipped},
		{ID: "eq-4", Outcome: OutcomeFailed, Error: "external system rejected payload: missing site"},
	}
	if !reflect.DeepEqual(resp.Results, want) {
		t.Errorf("results = %+v, want %+v", resp.Results, want)
	}
}

// Re-marshalling a decoded request must reproduce the platform's bytes, which
// catches an SDK-side tag rename in the request direction too (decoding alone
// would only catch a rename on a field the assertions above happen to cover).
func TestSyncRequest_RoundTripsPlatformWire(t *testing.T) {
	var req SyncRequest
	if err := json.Unmarshal([]byte(platformRequestJSON), &req); err != nil {
		t.Fatalf("decode: %v", err)
	}
	got, err := json.MarshalIndent(req, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if string(got) != platformRequestJSON {
		t.Errorf("round-tripped request differs from the platform's wire:\n got: %s\nwant: %s", got, platformRequestJSON)
	}
}

// The mode and outcome vocabularies are compared as literal strings, because
// they cross the wire as strings and the platform rejects an unrecognized
// outcome. A constant renamed on one side only is caught here.
func TestVocabulary_MatchesPlatformWireValues(t *testing.T) {
	if string(ModeBulk) != "bulk" || string(ModeChange) != "change" {
		t.Errorf("mode vocabulary drifted: bulk=%q change=%q", ModeBulk, ModeChange)
	}
	for want, o := range map[string]Outcome{
		"created": OutcomeCreated,
		"updated": OutcomeUpdated,
		"skipped": OutcomeSkipped,
		"failed":  OutcomeFailed,
	} {
		if string(o) != want {
			t.Errorf("outcome %q drifted to %q", want, o)
		}
		if !o.Valid() {
			t.Errorf("outcome %q reports invalid", o)
		}
	}
	if Outcome("done").Valid() {
		t.Error("unrecognized outcome reports valid; the platform would discard the whole batch")
	}
}

// Endpoint paths are part of the contract too — a component serving /sync
// instead of /egress/sync is unreachable, and nothing would fail until a real
// push.
func TestPaths_MatchPlatformContract(t *testing.T) {
	if PathSync != "/egress/sync" {
		t.Errorf("PathSync = %q", PathSync)
	}
	if PathEntityTypes != "/egress/entity-types" {
		t.Errorf("PathEntityTypes = %q", PathEntityTypes)
	}
	// Unprefixed on purpose: the platform-wide sidecar health convention.
	if PathHealthz != "/healthz" {
		t.Errorf("PathHealthz = %q", PathHealthz)
	}
}

// A colon-bearing class ID survives the wire unchanged, in both directions and at
// both levels (batch and per-entity).
//
// The platform stores `entity_type` as the source-native class ID and performs no
// translation outbound, so a namespaced id reaches a component verbatim. This test
// exists because the SDK is where a kit author would most plausibly be tempted to
// "clean up" such a value, and because the platform side of this exact confusion
// produced a real defect: composing a storage identifier from the class ID
// addressed a type that could not exist, and the run reported a successful push of
// nothing.
func TestClassID_ColonSurvivesTheWire(t *testing.T) {
	const classID = "brick:AHU"

	body := `{"tenant_id":"sjcs","external_system":"24k-core","entity_type":"brick:AHU",
	  "mode":"bulk","batch_id":"b-1","entities":[{"id":"eq-1","entity_type":"brick:AHU"}]}`

	var req SyncRequest
	if err := json.Unmarshal([]byte(body), &req); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if req.EntityType != classID {
		t.Errorf("batch entity_type = %q, want %q verbatim", req.EntityType, classID)
	}
	if len(req.Entities) != 1 || req.Entities[0].EntityType != classID {
		t.Errorf("entity entity_type = %+v, want %q verbatim", req.Entities, classID)
	}

	// And back out: the introspection reply must not normalize it either.
	out, err := json.Marshal(EntityTypesResponse{EntityTypes: []string{classID, "Equipment"}})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if got, want := string(out), `{"entity_types":["brick:AHU","Equipment"]}`; got != want {
		t.Errorf("entity-types reply = %s, want %s", got, want)
	}
}

// The homogeneity check compares class IDs as OPAQUE strings.
//
// Two ids that differ only by namespace prefix are different catalog entries, so a
// batch mixing them is genuinely non-homogeneous and must be rejected — a check
// that stripped the prefix before comparing would accept it and the component would
// map half the batch to the wrong target shape.
func TestClassID_HomogeneityIsExactNotPrefixInsensitive(t *testing.T) {
	impl := &stubComponent{sync: func(_ context.Context, _ *SyncRequest, b *Batch) error {
		b.Skipped("e1")
		b.Skipped("e2")
		return nil
	}}
	w := postSync(t, impl, SyncRequest{
		TenantID: "sjcs", ExternalSystem: "24k-core", EntityType: "brick:Equipment",
		Mode: ModeBulk, BatchID: "b-1",
		Entities: []Entity{
			{ID: "e1", EntityType: "brick:Equipment"},
			{ID: "e2", EntityType: "Equipment"}, // same suffix, DIFFERENT class ID
		},
	})
	if w.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400: %q and %q are different class IDs, so this "+
			"batch is not homogeneous", w.Code, "brick:Equipment", "Equipment")
	}
}

// The manifest half of this invariant is asserted in
// manifest.TestValidateEgressSyncs_AcceptsNamespacedClassID — the two must agree
// about what a legal entity type is, or a kit could declare a type it can never
// receive.
