package egress

import (
	"context"
	"encoding/json"
	"net/http"
	"reflect"
	"testing"
)

// Cross-repo wire drift guard.
//
// The platform's internal/egress structs and this package's are two independent
// declarations of ONE wire contract, living in different repositories. Nothing in
// either compiler sees the other, so a renamed JSON tag on either side is a
// silent, total integration break: an entity id that decodes to "" produces a
// batch the platform rejects as malformed, and it would pass every unit test in
// both repos.
//
// The fixtures below were GENERATED by marshalling the platform's own
// internal/egress.SyncRequest / SyncResponse (oga-platform, PR #814 branch
// feat/OGA-775-egress-sync at b076845a) and pasted verbatim. They are not
// hand-written from the design document, which would only prove the SDK agrees
// with a prose description.
//
// This guard catches drift on the SDK side of the pair. It cannot catch a
// platform-side rename by itself — that needs the mirror test in the platform
// repo, which imports this package and cross-decodes both directions.
const (
	platformRequestJSON = `{
  "tenant_id": "sjcs",
  "external_system": "24k-core",
  "entity_type": "Equipment",
  "mode": "bulk",
  "batch_id": "egress-sjcs-24k-core-Equipment-bulk-0001",
  "entities": [
    {
      "id": "eq-1",
      "entity_type": "Equipment",
      "properties": {
        "active": true,
        "floor": 3,
        "name": "AHU-1"
      }
    },
    {
      "id": "eq-2",
      "entity_type": "Equipment",
      "properties": {
        "name": "AHU-2"
      },
      "correlation": {
        "external_system": "24k-core",
        "external_record_id": "CORE-77"
      }
    },
    {
      "id": "eq-3",
      "entity_type": "Equipment"
    }
  ]
}`

	platformResponseJSON = `{
  "results": [
    {
      "id": "eq-1",
      "outcome": "created",
      "external_record_id": "CORE-90"
    },
    {
      "id": "eq-2",
      "outcome": "updated",
      "external_record_id": "CORE-77"
    },
    {
      "id": "eq-3",
      "outcome": "skipped"
    },
    {
      "id": "eq-4",
      "outcome": "failed",
      "error": "external system rejected payload: missing site"
    }
  ]
}`

	// The two PLATFORM-RESOLVED fields, which the fixtures above predate:
	// parent_refs (OGA-822) and type_ancestry (OGA-865). Generated the same way, by
	// marshalling the platform's own internal/egress.SyncRequest and pasting the
	// output verbatim — not written from the design document, which would only prove
	// the SDK agrees with prose.
	//
	// Unlike the fixtures above, this literal is RECONCILED: the platform holds the
	// same bytes in its own internal/egress/wire_golden_test.go and asserts that
	// marshalling produces them. That is what makes it a cross-repo guard instead of
	// each repo agreeing with itself — the fixture is the shared artifact, and a
	// rename or a reorder on EITHER side fails on that side. Keep the two copies
	// identical; changing one alone is the drift this exists to catch.
	//
	// Both fields are resolved server-side and neither is derivable from the entity's
	// own properties, so a tag rename is a silent routing break rather than a decode
	// error: parent_refs going missing sends a null foreign key, and type_ancestry
	// going missing sends a component back to the unreliable class_hierarchy property.
	//
	// The three entities cover the three shapes a component must handle: a leaf with
	// a full chain and an owner, a ROOT whose chain is one element (indistinguishable
	// on the wire from a leaf that resolved nothing, which is why absence is a
	// separate case), and an entity whose class the ontology does not define, where
	// the field is OMITTED rather than flattened.
	platformResolvedRefsRequestJSON = `{
  "tenant_id": "sjcs1",
  "external_system": "24k-core",
  "entity_type": "Location",
  "mode": "bulk",
  "batch_id": "sjcs1:core-egress-sync:Location:bulk:1:abc",
  "entities": [
    {
      "id": "019e38e3-room",
      "entity_type": "rec:Room",
      "properties": {
        "rdfs_label": "SAN 36A-L4-312"
      },
      "parent_refs": {
        "hasLocation": {
          "entity_id": "019e38e3-level",
          "external_record_id": "8f2c1d04-core-uuid"
        }
      },
      "type_ancestry": [
        "rec:Room",
        "rec:Space",
        "rec:Building",
        "rec:Site"
      ]
    },
    {
      "id": "019e38e3-site",
      "entity_type": "rec:Site",
      "type_ancestry": [
        "rec:Site"
      ]
    },
    {
      "id": "019e38e3-stale",
      "entity_type": "sjcs:Unregistered"
    }
  ]
}`
)

// A platform-marshalled request must decode into the SDK structs with every
// field populated. Asserting field VALUES (not just a nil error) is the point:
// json.Unmarshal ignores a field whose tag does not match, so a renamed tag
// decodes without error and silently yields a zero value.
func TestSyncRequest_DecodesPlatformWire(t *testing.T) {
	var req SyncRequest
	if err := json.Unmarshal([]byte(platformRequestJSON), &req); err != nil {
		t.Fatalf("decode platform request: %v", err)
	}
	if req.TenantID != "sjcs" {
		t.Errorf("tenant_id = %q, want sjcs", req.TenantID)
	}
	if req.ExternalSystem != "24k-core" {
		t.Errorf("external_system = %q, want 24k-core", req.ExternalSystem)
	}
	if req.EntityType != "Equipment" {
		t.Errorf("entity_type = %q, want Equipment", req.EntityType)
	}
	if req.Mode != ModeBulk {
		t.Errorf("mode = %q, want %q", req.Mode, ModeBulk)
	}
	if req.BatchID != "egress-sjcs-24k-core-Equipment-bulk-0001" {
		t.Errorf("batch_id = %q", req.BatchID)
	}
	if len(req.Entities) != 3 {
		t.Fatalf("entities = %d, want 3", len(req.Entities))
	}

	first := req.Entities[0]
	if first.ID != "eq-1" || first.EntityType != "Equipment" {
		t.Errorf("entities[0] = %+v", first)
	}
	// A JSON number decodes into any as float64; a kit mapping properties must
	// expect that, so the fixture carries one and the test pins the type.
	if got, ok := first.Properties["floor"].(float64); !ok || got != 3 {
		t.Errorf("entities[0].properties[floor] = %#v, want float64(3)", first.Properties["floor"])
	}
	if first.Properties["name"] != "AHU-1" || first.Properties["active"] != true {
		t.Errorf("entities[0].properties = %#v", first.Properties)
	}
	if first.Correlation != nil {
		t.Errorf("entities[0].correlation = %+v, want nil (uncorrelated ⇒ create)", first.Correlation)
	}

	second := req.Entities[1]
	if second.Correlation == nil {
		t.Fatal("entities[1].correlation is nil: an already-correlated entity would be re-created, duplicating the external record")
	}
	if second.Correlation.ExternalSystem != "24k-core" || second.Correlation.ExternalRecordID != "CORE-77" {
		t.Errorf("entities[1].correlation = %+v", second.Correlation)
	}

	if third := req.Entities[2]; len(third.Properties) != 0 {
		t.Errorf("entities[2].properties = %#v, want empty (omitempty)", third.Properties)
	}
}

// An SDK-marshalled response must reproduce the platform's wire bytes exactly,
// including which fields omitempty drops.
func TestSyncResponse_MarshalsToPlatformWire(t *testing.T) {
	resp := SyncResponse{Results: []SyncResult{
		{ID: "eq-1", Outcome: OutcomeCreated, ExternalRecordID: "CORE-90"},
		{ID: "eq-2", Outcome: OutcomeUpdated, ExternalRecordID: "CORE-77"},
		{ID: "eq-3", Outcome: OutcomeSkipped},
		{ID: "eq-4", Outcome: OutcomeFailed, Error: "external system rejected payload: missing site"},
	}}
	got, err := json.MarshalIndent(resp, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if string(got) != platformResponseJSON {
		t.Errorf("SDK response wire differs from the platform's:\n got: %s\nwant: %s", got, platformResponseJSON)
	}
}

// And the reverse direction: the platform's response bytes decode into the SDK
// structs unchanged. This is what a kit-side test harness relies on.
func TestSyncResponse_DecodesPlatformWire(t *testing.T) {
	var resp SyncResponse
	if err := json.Unmarshal([]byte(platformResponseJSON), &resp); err != nil {
		t.Fatalf("decode platform response: %v", err)
	}
	want := []SyncResult{
		{ID: "eq-1", Outcome: OutcomeCreated, ExternalRecordID: "CORE-90"},
		{ID: "eq-2", Outcome: OutcomeUpdated, ExternalRecordID: "CORE-77"},
		{ID: "eq-3", Outcome: OutcomeSkipped},
		{ID: "eq-4", Outcome: OutcomeFailed, Error: "external system rejected payload: missing site"},
	}
	if !reflect.DeepEqual(resp.Results, want) {
		t.Errorf("results = %+v, want %+v", resp.Results, want)
	}
}

// Re-marshalling a decoded request must reproduce the platform's bytes, which
// catches an SDK-side tag rename in the request direction too (decoding alone
// would only catch a rename on a field the assertions above happen to cover).
func TestSyncRequest_RoundTripsPlatformWire(t *testing.T) {
	var req SyncRequest
	if err := json.Unmarshal([]byte(platformRequestJSON), &req); err != nil {
		t.Fatalf("decode: %v", err)
	}
	got, err := json.MarshalIndent(req, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if string(got) != platformRequestJSON {
		t.Errorf("round-tripped request differs from the platform's wire:\n got: %s\nwant: %s", got, platformRequestJSON)
	}
}

// The mode and outcome vocabularies are compared as literal strings, because
// they cross the wire as strings and the platform rejects an unrecognized
// outcome. A constant renamed on one side only is caught here.
func TestVocabulary_MatchesPlatformWireValues(t *testing.T) {
	if string(ModeBulk) != "bulk" || string(ModeChange) != "change" {
		t.Errorf("mode vocabulary drifted: bulk=%q change=%q", ModeBulk, ModeChange)
	}
	for want, o := range map[string]Outcome{
		"created": OutcomeCreated,
		"updated": OutcomeUpdated,
		"skipped": OutcomeSkipped,
		"failed":  OutcomeFailed,
	} {
		if string(o) != want {
			t.Errorf("outcome %q drifted to %q", want, o)
		}
		if !o.Valid() {
			t.Errorf("outcome %q reports invalid", o)
		}
	}
	if Outcome("done").Valid() {
		t.Error("unrecognized outcome reports valid; the platform would discard the whole batch")
	}
}

// Endpoint paths are part of the contract too — a component serving /sync
// instead of /egress/sync is unreachable, and nothing would fail until a real
// push.
func TestPaths_MatchPlatformContract(t *testing.T) {
	if PathSync != "/egress/sync" {
		t.Errorf("PathSync = %q", PathSync)
	}
	// Unprefixed on purpose: the platform-wide sidecar health convention.
	if PathHealthz != "/healthz" {
		t.Errorf("PathHealthz = %q", PathHealthz)
	}
}

// A colon-bearing class ID survives the wire unchanged, in both directions and at
// both levels (batch and per-entity).
//
// The platform stores `entity_type` as the source-native class ID and performs no
// translation outbound, so a namespaced id reaches a component verbatim. This test
// exists because the SDK is where a kit author would most plausibly be tempted to
// "clean up" such a value, and because the platform side of this exact confusion
// produced a real defect: composing a storage identifier from the class ID
// addressed a type that could not exist, and the run reported a successful push of
// nothing.
func TestClassID_ColonSurvivesTheWire(t *testing.T) {
	const classID = "brick:AHU"

	body := `{"tenant_id":"sjcs","external_system":"24k-core","entity_type":"brick:AHU",
	  "mode":"bulk","batch_id":"b-1","entities":[{"id":"eq-1","entity_type":"brick:AHU"}]}`

	var req SyncRequest
	if err := json.Unmarshal([]byte(body), &req); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if req.EntityType != classID {
		t.Errorf("batch entity_type = %q, want %q verbatim", req.EntityType, classID)
	}
	if len(req.Entities) != 1 || req.Entities[0].EntityType != classID {
		t.Errorf("entity entity_type = %+v, want %q verbatim", req.Entities, classID)
	}

}

// The homogeneity check compares class IDs as OPAQUE strings.
//
// Two ids that differ only by namespace prefix are different catalog entries, so a
// batch mixing them is genuinely non-homogeneous and must be rejected — a check
// that stripped the prefix before comparing would accept it and the component would
// map half the batch to the wrong target shape.
func TestClassID_HomogeneityIsExactNotPrefixInsensitive(t *testing.T) {
	impl := &stubComponent{sync: func(_ context.Context, _ *SyncRequest, b *Batch) error {
		b.Skipped("e1")
		b.Skipped("e2")
		return nil
	}}
	w := postSync(t, impl, SyncRequest{
		TenantID: "sjcs", ExternalSystem: "24k-core", EntityType: "brick:Equipment",
		Mode: ModeBulk, BatchID: "b-1",
		Entities: []Entity{
			{ID: "e1", EntityType: "brick:Equipment"},
			{ID: "e2", EntityType: "Equipment"}, // same suffix, DIFFERENT class ID
		},
	})
	if w.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400: %q and %q are different class IDs, so this "+
			"batch is not homogeneous", w.Code, "brick:Equipment", "Equipment")
	}
}

// The manifest half of this invariant is asserted in
// manifest.TestValidateEgressSyncs_AcceptsNamespacedClassID — the two must agree
// about what a legal entity type is, or a kit could declare a type it can never
// receive.

// The two reserved parent_refs keys are WIRE LITERALS, pinned here.
//
// A component matches them byte-for-byte to read a type reference or an ontology
// parent, and the platform holds its own copy of both constants. Two repos with
// the same literal is exactly the shape that drifts, and the drift would be
// silent: a renamed key means the lookup misses, the reference reads as absent,
// and "absent" is a LEGAL answer meaning "this record is a root" — so every
// affected record would be pushed with a null foreign key and the run would
// report success.
//
// If this test ever needs changing, the platform's internal/egress constants have
// to change in the same breath, and every published kit needs a re-release.
func TestParentRefKeys_AreWireLiterals(t *testing.T) {
	if TypeRefKey != "type_ref" {
		t.Errorf("TypeRefKey = %q, want %q", TypeRefKey, "type_ref")
	}
	if OntologyParentRefKey != "parent_type" {
		t.Errorf("OntologyParentRefKey = %q, want %q", OntologyParentRefKey, "parent_type")
	}
	// And they must stay distinct from each other: they can appear in the same map
	// type, and collapsing them would make a type reference indistinguishable from
	// an ontology parent.
	if TypeRefKey == OntologyParentRefKey {
		t.Fatal("the two reserved keys are equal; a type reference would be indistinguishable " +
			"from an ontology parent")
	}
}

// The platform-resolved fields decode with every element populated, IN ORDER.
//
// Order is the contract for type_ancestry, not a formatting detail: it is
// most-specific-first, so a component matching against its declared roots walks
// from index 0 outward. A reversed chain would decode without error and route every
// entity to the wrong target.
func TestSyncRequest_DecodesPlatformResolvedFields(t *testing.T) {
	var req SyncRequest
	if err := json.Unmarshal([]byte(platformResolvedRefsRequestJSON), &req); err != nil {
		t.Fatalf("decode platform request: %v", err)
	}
	if len(req.Entities) != 3 {
		t.Fatalf("entities = %d, want 3", len(req.Entities))
	}

	leaf := req.Entities[0]
	wantChain := []string{"rec:Room", "rec:Space", "rec:Building", "rec:Site"}
	if !reflect.DeepEqual(leaf.TypeAncestry, wantChain) {
		t.Errorf("type_ancestry = %v, want %v (leaf first, in order)", leaf.TypeAncestry, wantChain)
	}
	if got := leaf.ParentRefs["hasLocation"].ExternalRecordID; got != "8f2c1d04-core-uuid" {
		t.Errorf("parent_refs[hasLocation].external_record_id = %q", got)
	}

	// A ROOT arrives as a ONE-ELEMENT chain naming itself, never as an empty one.
	// That is what lets a component treat "my declared root is in this chain" as one
	// rule for every entity instead of special-casing the top of the hierarchy —
	// which is precisely where the class_hierarchy property failed.
	if root := req.Entities[1]; !reflect.DeepEqual(root.TypeAncestry, []string{"rec:Site"}) {
		t.Errorf("root type_ancestry = %v, want [rec:Site]", root.TypeAncestry)
	}

	// A class the ontology does not define carries NO chain. Absence means "the
	// platform has no ancestry to state" and must not be read as a root: the platform
	// deliberately does not flatten it to a one-element chain, because that would be
	// byte-identical to entities[1] above.
	if stale := req.Entities[2]; stale.TypeAncestry != nil {
		t.Errorf("undefined class carried type_ancestry = %v, want none", stale.TypeAncestry)
	}
}

// And the reverse direction, byte-for-byte.
//
// Decoding alone would only catch a rename on a field the assertions above happen to
// read; re-marshalling also pins FIELD ORDER. This half holds the SDK to the shared
// fixture; the platform's TestSyncRequest_MarshalsToTheSharedWireFixture holds the
// platform to the same bytes. Neither test alone proves the two structs agree — the
// pair does, provided the literal stays identical in both repos.
func TestSyncRequest_RoundTripsPlatformResolvedFields(t *testing.T) {
	var req SyncRequest
	if err := json.Unmarshal([]byte(platformResolvedRefsRequestJSON), &req); err != nil {
		t.Fatalf("decode: %v", err)
	}
	got, err := json.MarshalIndent(req, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if string(got) != platformResolvedRefsRequestJSON {
		t.Errorf("round-tripped request differs from the platform's wire:\n got: %s\nwant: %s",
			got, platformResolvedRefsRequestJSON)
	}
}

// The JSON TAGS on the platform-resolved fields are pinned as wire literals.
//
// Read off the struct by reflection rather than inferred from a decode, so a rename
// fails HERE with the old and new names in the message instead of surfacing as a
// field that silently decodes to nil. Both are omitempty, which is what keeps the
// older fixtures in this file valid byte-for-byte.
func TestPlatformResolvedFieldTags_AreWireLiterals(t *testing.T) {
	for field, want := range map[string]string{
		"ParentRefs":   "parent_refs,omitempty",
		"TypeAncestry": "type_ancestry,omitempty",
	} {
		f, ok := reflect.TypeOf(Entity{}).FieldByName(field)
		if !ok {
			t.Errorf("Entity has no field %s", field)
			continue
		}
		if got := f.Tag.Get("json"); got != want {
			t.Errorf("Entity.%s json tag = %q, want %q — the platform serializes the latter",
				field, got, want)
		}
	}
}

// A reserved key round-trips through parent_refs like any edge-keyed entry, which
// is the property that lets a component read ONE map with one value shape.
func TestParentRefs_ReservedKeysDecodeLikeEdgeKeys(t *testing.T) {
	const body = `{
	  "id": "e1",
	  "entity_type": "brick:AHU",
	  "parent_refs": {
	    "hasLocation": {"entity_id": "loc-1", "external_record_id": "SPACE-9"},
	    "type_ref":    {"entity_id": "brick:AHU", "external_record_id": "CLASS-4"}
	  }
	}`
	var e Entity
	if err := json.Unmarshal([]byte(body), &e); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if got := e.ParentRefs["hasLocation"].ExternalRecordID; got != "SPACE-9" {
		t.Errorf("edge-keyed ref = %q, want SPACE-9", got)
	}
	if got := e.ParentRefs[TypeRefKey].ExternalRecordID; got != "CLASS-4" {
		t.Errorf("type_ref ref = %q, want CLASS-4 — a reserved key must decode from the "+
			"same map as an edge key, with the same value shape", got)
	}
}
